version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: make release
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
